import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";
import { access, copyFile, mkdir, readFile, writeFile } from "fs/promises";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = (process.argv[2] === "production");
const syncRequested = process.env.OBSIDIAN_SYNC_ON_BUILD === "1";
const artifactFiles = ["main.js", "manifest.json", "styles.css"];

const vaultRoot = process.env.OBSIDIAN_VAULT_DIR
    || "/Users/goryugo/Library/Mobile Documents/iCloud~md~obsidian/Documents/Obsidian_local";
const pluginId = process.env.OBSIDIAN_PLUGIN_ID || "llr";
const targetRoots = [".obsidian", ".iphone"];
const pluginDirNames = (
    process.env.OBSIDIAN_PLUGIN_DIR_NAMES
        ? process.env.OBSIDIAN_PLUGIN_DIR_NAMES.split(",").map((s) => s.trim()).filter(Boolean)
        : [pluginId]
);
const legacyPluginIdsToDisable = (
    process.env.OBSIDIAN_DISABLE_PLUGIN_IDS
        ? process.env.OBSIDIAN_DISABLE_PLUGIN_IDS.split(",").map((s) => s.trim()).filter(Boolean)
        : []
).filter((id) => id !== pluginId);
const targetDirs = (
    process.env.OBSIDIAN_PLUGIN_TARGETS
        ? process.env.OBSIDIAN_PLUGIN_TARGETS.split(",").map((p) => p.trim()).filter(Boolean)
        : targetRoots.flatMap((root) =>
            pluginDirNames.map((dirName) => path.join(vaultRoot, root, "plugins", dirName))
        )
);
const communityPluginFiles = targetRoots.map((root) => path.join(vaultRoot, root, "community-plugins.json"));

const pathExists = async (filePath) => {
    try {
        await access(filePath);
        return true;
    } catch {
        return false;
    }
};

const syncArtifacts = async () => {
    for (const dir of targetDirs) {
        await mkdir(dir, { recursive: true });
        for (const fileName of artifactFiles) {
            if (!(await pathExists(fileName))) continue;
            await copyFile(fileName, path.join(dir, fileName));
        }
        console.log(`[sync] copied artifacts to ${dir}`);
    }
};

const ensureCommunityPluginEnabled = async () => {
    for (const communityFile of communityPluginFiles) {
        try {
            const raw = await readFile(communityFile, "utf-8");
            const list = JSON.parse(raw);
            if (!Array.isArray(list)) continue;
            const cleaned = list.filter((id) => !legacyPluginIdsToDisable.includes(id));
            if (!cleaned.includes(pluginId)) {
                cleaned.push(pluginId);
            }
            const changed = cleaned.length !== list.length || cleaned.some((id, i) => id !== list[i]);
            if (changed) {
                await writeFile(communityFile, `${JSON.stringify(cleaned, null, 2)}\n`, "utf-8");
                const removed = list.filter((id) => legacyPluginIdsToDisable.includes(id));
                if (removed.length > 0) {
                    console.log(`[sync] removed legacy plugin ids (${removed.join(", ")}) from ${communityFile}`);
                }
                if (!list.includes(pluginId)) {
                    console.log(`[sync] enabled ${pluginId} in ${communityFile}`);
                }
            }
        } catch (error) {
            console.warn(`[sync] could not update ${communityFile}: ${error.message}`);
        }
    }
};

const syncPlugin = {
    name: "sync-obsidian-plugin-files",
    setup(build) {
        build.onEnd(async (result) => {
            if (result.errors.length > 0) return;
            if (!syncRequested) {
                console.log("[sync] skipped local Obsidian deploy (set OBSIDIAN_SYNC_ON_BUILD=1 to enable)");
                return;
            }
            await syncArtifacts();
            await ensureCommunityPluginEnabled();
        });
    }
};

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/closebrackets",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/comment",
        "@codemirror/fold",
        "@codemirror/gutter",
        "@codemirror/highlight",
        "@codemirror/history",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/matchbrackets",
        "@codemirror/panel",
        "@codemirror/rangeset",
        "@codemirror/rectangular-selection",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/stream-parser",
        "@codemirror/text",
        "@codemirror/tooltip",
        "@codemirror/view",
        ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    platform: "node", // Obsidian plugins run in Node context within Electron
    plugins: [syncPlugin]
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
